Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  UseCache: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/SymbolArray:
  EnforcedStyle: brackets
